### ISSUE TITLE
Разработка прототипа

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/PKKGW#11]
В Главе 1(исследовательская часть), в раздел  _Перечень задач, подлежащих решению..._ я добавил следующую задачу:

6.	Создание прототипа приложения.
Для тестирования работы алгоритмов поиска земельных участков необходим прототип, который позволит определить точность, скорость работы и другие параметры разработанных алгоритмов. Так же, он позволит получить первый отклик об интерфейсе приложения.

Описание процесса создания я запихнул в конструкторскую часть
[Разработка прототипа.docx](https://github.com/Lakovshchikov/PKKGW/files/2971296/default.docx)

**Comment by wldmr-key** [comment]
да, нормально
