### ISSUE TITLE
Технологии разработки

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/PKKGW#13]
@wldmr-key  А не страшно, если я немного привру? Скажу что клиент у меня разделяется на такие модули:
![image](https://user-images.githubusercontent.com/43318877/55494918-6f80fd00-5644-11e9-8520-e9e707e1e557.png)
Если что, схему приведу в порядок, это черновой вариант.

На самом деле у меня нет PKKGW и Main. В качестве Main по факту выступает модуль с UI. Но об этом говорить я не очень хочу, а так как на рисунке вроде более-менее логично выглядит.

**Comment by Lakovshchikov** [comment]
И еще вопрос. А куски кода вставлять нужно? Или можно по желанию и при необходимости набрать объема? Я просто не особо понимаю - это будет плюсом или минусом.

**Comment by Lakovshchikov** [comment]
Пока писал, подумал что это вообще может быть тут лишним. Это относится к архитектуре (о которой я ничего не говорил нигде). Есть ли смысл немного рассказать тут?

**Comment by wldmr-key** [comment]
Последнее справедливо. Это, действительно, не технологии, а архитектура приложения. Твои преувеличения вполне допустимы.
Код в твоей работе, думаю, не нужен совсем. Где-то у тебя уже были, я помню, примеры обращения к сервисам - этого вполне достаточно.

**Comment by Lakovshchikov** [comment]
[Технологии разработки.docx](https://github.com/Lakovshchikov/PKKGW/files/3054101/default.docx)

**Comment by wldmr-key** [comment]
ну да, где-то так
