### ISSUE TITLE
Описание предметной области

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/PKKGW#3]
[Описание предметной области.docx](https://github.com/Lakovshchikov/PKKGW/files/2921856/default.docx)
Полностью взял с курсача

**Comment by wldmr-key** [comment]
В принципе все хорошо и можно так и оставить. Можно дополнить рассказ о том, что нужно сделать, пояснениями **как** это делается в настоящее время (каким средствами и каких требует затрат/усилий). Хотя, в принципе, задача решалась бы легко, имей инвестор удобный доступ к необходимой информации

**Comment by Lakovshchikov** [comment]
[Описание предметной области.docx](https://github.com/Lakovshchikov/PKKGW/files/2970808/default.docx)

**Comment by wldmr-key** [comment]
нормально. Термин "сличение" режет глаза. Если он общепринят в профессиональной среде, то оставь, если это твое изобретение, лучше заменить на сопоставление
