### ISSUE TITLE
Перечень задач, подлежащих решению в процессе разработки

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/PKKGW#4]
[Перечень задач, подлежащих решению в процессе разработки.docx](https://github.com/Lakovshchikov/PKKGW/files/2921867/default.docx)

**Comment by wldmr-key** [comment]
Нуждается в спелл-чекинге и вычитыванию несообразностей

Я бы посоветовал приблизить содержание к реальной жизни и включить в задачи разработку прототипа, который позволил бы оценить требования к пользовательскому интерфейсу, определиться с росреестровскими данными и собственными алгоритмами

**Comment by Lakovshchikov** [comment]
А разработка прототипа не является конечной целью?
[Перечень задач, подлежащих решению в процессе разработки.docx](https://github.com/Lakovshchikov/PKKGW/files/2948384/default.docx)

**Comment by wldmr-key** [comment]
я имел в виду прошлогоднюю поделку. Впрочем, я не настаиваю
