### ISSUE TITLE
Анализ аналогов

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/PKKGW#5]
[Анализ аналогов.docx](https://github.com/Lakovshchikov/PKKGW/files/2921875/default.docx)

**Comment by wldmr-key** [comment]
По сути - прекрасно. По наполнению - фраза "Указанные программы имеют сложный для простого пользователя интерфейс, а так же предполагают, что у пользователя уже есть официально приобретенная подоснова" нуждается в расшифровке на пару-тройку (или больше) абзацев. Ты же инженер! Дай количественные характеристики, которые конкуренты с гордостью сами выкатывают. Количество функций, цена, варианты поставки, стоимость обучения - вариантов много...

**Comment by Lakovshchikov** [comment]
[Анализ аналогов.docx](https://github.com/Lakovshchikov/PKKGW/files/2948448/default.docx)

**Comment by wldmr-key** [comment]
красота!
