### ISSUE TITLE
Разработка структуры программной системы

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/PKKGW#6]
[РСПС v2.docx](https://github.com/Lakovshchikov/PKKGW/files/2927684/v2.docx)
Убрал упоминания про СанПин, мне кажется он был лишний. Добавил еще одну задачу для работы с объектом кап. строительства.
1 задача
![image](https://user-images.githubusercontent.com/43318877/53753724-01b9a800-3ec3-11e9-94ce-9099453b567a.png)
2 задача
![image](https://user-images.githubusercontent.com/43318877/53753752-10a05a80-3ec3-11e9-8902-8ec39b1b64f6.png)

**Comment by wldmr-key** [comment]
нормально
