### ISSUE TITLE
Концептуальная схема данных

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/PKKGW#7]
[Концептуальная схема данных.docx](https://github.com/Lakovshchikov/PKKGW/files/2927705/default.docx)
Добавил одну сущность, как это адекватно отобразить в схеме не придумал пока. Стрелки же не могут пересекаться?
![image](https://user-images.githubusercontent.com/43318877/53753897-77257880-3ec3-11e9-8ac7-536607a4d46d.png)

**Comment by wldmr-key** [comment]
возможно, ОКС и земельный участок - разные сущности, разный атрибутный состав, разные связи с пользователем и друг с другом

**Comment by Lakovshchikov** [comment]
Это разные сущности, пока не придумал как их расположить. Связи же не могут пересекаться?

**Comment by Lakovshchikov** [comment]
Вот что получилось. Отличия:
1. Вынес отдельно сущность ОКС.
2. Связь между Отчетом и Границами  СЗЗ стала 1 к 1. Так как Границы СЗЗ связаны с участком, и если они не меняются, то отчет тоже не меняется.
3. Связь Рабочая облать - Границы СЗЗ - связь 1 ко многим, так как можно отображать одновременно границы ЗУ и ОКС.

![image](https://user-images.githubusercontent.com/43318877/54082609-8d02c580-4329-11e9-8b94-f9145eb7e3c5.png)

**Comment by wldmr-key** [comment]
очень большие вопросы - проговорим при живой встрече - держи наготове
