### ISSUE TITLE
Пользовательские сценарии

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/PKKGW#8]
Добавил пару новых, отредактировал остальные с учетом веб.
[Пользовательские сценарии.docx](https://github.com/Lakovshchikov/PKKGW/files/2927710/default.docx)

**Comment by wldmr-key** [comment]
3. Загрузка состояния рабочей области - расширение - если файл поврежден, то, наверное, пользователь может заново ее настроить

а так, вроде, нормально (uml - это, действительно, uml?)
