### ISSUE TITLE
Алгоритмы обработки информации

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/PKKGW#9]
[Алгоритмы обработки информации.docx](https://github.com/Lakovshchikov/PKKGW/files/2949314/default.docx)
Для заливки я использовал другой метод, честно сворованный из интернета. Прекрасно работает, и я не особо разбирался как. Можно его не описывать, а оставить как есть?

**Comment by wldmr-key** [comment]
вполне нормально
